[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_ENV = "production"

[dev]
  command = "npm run dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200