name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Netlify
        if: github.event_name == 'push' && secrets.NETLIFY_AUTH_TOKEN != ''
        run: |
          npm install netlify-cli -g
          netlify deploy --prod --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}

      # - name: Deploy to Vercel
      #   if: github.event_name == 'push' && secrets.VERCEL_TOKEN != ''
      #   run: |
      #     npm install -g vercel
      #     vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm